### ISSUE TITLE
InttelijでJavaのmavenが動かない状態

### ISSUE THREAD

**Issue by rami2076** [rami2076/a-star-by-java#4]
![image](https://user-images.githubusercontent.com/43103316/102000424-9d2fac00-3d2a-11eb-9158-a5b7d651ab7c.png)

**Comment by SeasonFish** [comment]
mavenのリポジトリを参照する時、パスにあるスペースが文字化けしたのが原因です。
リポジトリとsettings.xmlを別のディレクトリに移動して、参照パスを設定し直したら解決しました。

念のためGitの設定も以下のように変更しました。
```
git config core.autocrlf=false 
git config core.quotepath=false
git config --global core.pager "LESSCHARSET=utf-8 less"
```
